//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Controller.dk.gls.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsShopFinderSoap", Namespace="http://gls.dk/webservices/")]
    public partial class wsShopFinder : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOneParcelShopOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllParcelShopsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetParcelShopsInZipcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchNearestParcelShopsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetParcelShopDropPointOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsShopFinder() {
            this.Url = global::Controller.Properties.Settings.Default.Controller_dk_gls_www_wsShopFinder;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOneParcelShopCompletedEventHandler GetOneParcelShopCompleted;
        
        /// <remarks/>
        public event GetAllParcelShopsCompletedEventHandler GetAllParcelShopsCompleted;
        
        /// <remarks/>
        public event GetParcelShopsInZipcodeCompletedEventHandler GetParcelShopsInZipcodeCompleted;
        
        /// <remarks/>
        public event SearchNearestParcelShopsCompletedEventHandler SearchNearestParcelShopsCompleted;
        
        /// <remarks/>
        public event GetParcelShopDropPointCompletedEventHandler GetParcelShopDropPointCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gls.dk/webservices/GetOneParcelShop", RequestNamespace="http://gls.dk/webservices/", ResponseNamespace="http://gls.dk/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PakkeshopData GetOneParcelShop(string ParcelShopNumber) {
            object[] results = this.Invoke("GetOneParcelShop", new object[] {
                        ParcelShopNumber});
            return ((PakkeshopData)(results[0]));
        }
        
        /// <remarks/>
        public void GetOneParcelShopAsync(string ParcelShopNumber) {
            this.GetOneParcelShopAsync(ParcelShopNumber, null);
        }
        
        /// <remarks/>
        public void GetOneParcelShopAsync(string ParcelShopNumber, object userState) {
            if ((this.GetOneParcelShopOperationCompleted == null)) {
                this.GetOneParcelShopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOneParcelShopOperationCompleted);
            }
            this.InvokeAsync("GetOneParcelShop", new object[] {
                        ParcelShopNumber}, this.GetOneParcelShopOperationCompleted, userState);
        }
        
        private void OnGetOneParcelShopOperationCompleted(object arg) {
            if ((this.GetOneParcelShopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOneParcelShopCompleted(this, new GetOneParcelShopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gls.dk/webservices/GetAllParcelShops", RequestNamespace="http://gls.dk/webservices/", ResponseNamespace="http://gls.dk/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PakkeshopData[] GetAllParcelShops(string countryIso3166A2) {
            object[] results = this.Invoke("GetAllParcelShops", new object[] {
                        countryIso3166A2});
            return ((PakkeshopData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllParcelShopsAsync(string countryIso3166A2) {
            this.GetAllParcelShopsAsync(countryIso3166A2, null);
        }
        
        /// <remarks/>
        public void GetAllParcelShopsAsync(string countryIso3166A2, object userState) {
            if ((this.GetAllParcelShopsOperationCompleted == null)) {
                this.GetAllParcelShopsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllParcelShopsOperationCompleted);
            }
            this.InvokeAsync("GetAllParcelShops", new object[] {
                        countryIso3166A2}, this.GetAllParcelShopsOperationCompleted, userState);
        }
        
        private void OnGetAllParcelShopsOperationCompleted(object arg) {
            if ((this.GetAllParcelShopsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllParcelShopsCompleted(this, new GetAllParcelShopsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gls.dk/webservices/GetParcelShopsInZipcode", RequestNamespace="http://gls.dk/webservices/", ResponseNamespace="http://gls.dk/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PakkeshopData[] GetParcelShopsInZipcode(string zipcode, string countryIso3166A2) {
            object[] results = this.Invoke("GetParcelShopsInZipcode", new object[] {
                        zipcode,
                        countryIso3166A2});
            return ((PakkeshopData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetParcelShopsInZipcodeAsync(string zipcode, string countryIso3166A2) {
            this.GetParcelShopsInZipcodeAsync(zipcode, countryIso3166A2, null);
        }
        
        /// <remarks/>
        public void GetParcelShopsInZipcodeAsync(string zipcode, string countryIso3166A2, object userState) {
            if ((this.GetParcelShopsInZipcodeOperationCompleted == null)) {
                this.GetParcelShopsInZipcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetParcelShopsInZipcodeOperationCompleted);
            }
            this.InvokeAsync("GetParcelShopsInZipcode", new object[] {
                        zipcode,
                        countryIso3166A2}, this.GetParcelShopsInZipcodeOperationCompleted, userState);
        }
        
        private void OnGetParcelShopsInZipcodeOperationCompleted(object arg) {
            if ((this.GetParcelShopsInZipcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetParcelShopsInZipcodeCompleted(this, new GetParcelShopsInZipcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gls.dk/webservices/SearchNearestParcelShops", RequestNamespace="http://gls.dk/webservices/", ResponseNamespace="http://gls.dk/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ParcelShopSearchResult SearchNearestParcelShops(string street, string zipcode, string countryIso3166A2, int Amount) {
            object[] results = this.Invoke("SearchNearestParcelShops", new object[] {
                        street,
                        zipcode,
                        countryIso3166A2,
                        Amount});
            return ((ParcelShopSearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void SearchNearestParcelShopsAsync(string street, string zipcode, string countryIso3166A2, int Amount) {
            this.SearchNearestParcelShopsAsync(street, zipcode, countryIso3166A2, Amount, null);
        }
        
        /// <remarks/>
        public void SearchNearestParcelShopsAsync(string street, string zipcode, string countryIso3166A2, int Amount, object userState) {
            if ((this.SearchNearestParcelShopsOperationCompleted == null)) {
                this.SearchNearestParcelShopsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchNearestParcelShopsOperationCompleted);
            }
            this.InvokeAsync("SearchNearestParcelShops", new object[] {
                        street,
                        zipcode,
                        countryIso3166A2,
                        Amount}, this.SearchNearestParcelShopsOperationCompleted, userState);
        }
        
        private void OnSearchNearestParcelShopsOperationCompleted(object arg) {
            if ((this.SearchNearestParcelShopsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchNearestParcelShopsCompleted(this, new SearchNearestParcelShopsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gls.dk/webservices/GetParcelShopDropPoint", RequestNamespace="http://gls.dk/webservices/", ResponseNamespace="http://gls.dk/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ParcelShopSearchResult GetParcelShopDropPoint(string street, string zipcode, string countryIso3166A2, int Amount) {
            object[] results = this.Invoke("GetParcelShopDropPoint", new object[] {
                        street,
                        zipcode,
                        countryIso3166A2,
                        Amount});
            return ((ParcelShopSearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetParcelShopDropPointAsync(string street, string zipcode, string countryIso3166A2, int Amount) {
            this.GetParcelShopDropPointAsync(street, zipcode, countryIso3166A2, Amount, null);
        }
        
        /// <remarks/>
        public void GetParcelShopDropPointAsync(string street, string zipcode, string countryIso3166A2, int Amount, object userState) {
            if ((this.GetParcelShopDropPointOperationCompleted == null)) {
                this.GetParcelShopDropPointOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetParcelShopDropPointOperationCompleted);
            }
            this.InvokeAsync("GetParcelShopDropPoint", new object[] {
                        street,
                        zipcode,
                        countryIso3166A2,
                        Amount}, this.GetParcelShopDropPointOperationCompleted, userState);
        }
        
        private void OnGetParcelShopDropPointOperationCompleted(object arg) {
            if ((this.GetParcelShopDropPointCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetParcelShopDropPointCompleted(this, new GetParcelShopDropPointCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public partial class PakkeshopData {
        
        private string numberField;
        
        private string companyNameField;
        
        private string streetnameField;
        
        private string streetname2Field;
        
        private string zipCodeField;
        
        private string cityNameField;
        
        private string countryCodeField;
        
        private string countryCodeISO3166A2Field;
        
        private string telephoneField;
        
        private string longitudeField;
        
        private string latitudeField;
        
        private int distanceMetersAsTheCrowFliesField;
        
        private Weekday[] openingHoursField;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Streetname {
            get {
                return this.streetnameField;
            }
            set {
                this.streetnameField = value;
            }
        }
        
        /// <remarks/>
        public string Streetname2 {
            get {
                return this.streetname2Field;
            }
            set {
                this.streetname2Field = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCodeISO3166A2 {
            get {
                return this.countryCodeISO3166A2Field;
            }
            set {
                this.countryCodeISO3166A2Field = value;
            }
        }
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public int DistanceMetersAsTheCrowFlies {
            get {
                return this.distanceMetersAsTheCrowFliesField;
            }
            set {
                this.distanceMetersAsTheCrowFliesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Weekday[] OpeningHours {
            get {
                return this.openingHoursField;
            }
            set {
                this.openingHoursField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public partial class Weekday {
        
        private Day dayField;
        
        private Hour openAtField;
        
        private Break[] breaksField;
        
        /// <remarks/>
        public Day day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        public Hour openAt {
            get {
                return this.openAtField;
            }
            set {
                this.openAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Break[] breaks {
            get {
                return this.breaksField;
            }
            set {
                this.breaksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public enum Day {
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Tuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
        
        /// <remarks/>
        Sunday,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public partial class Hour {
        
        private string fromField;
        
        private string toField;
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public partial class ParcelShopSearchResult {
        
        private AccuracyLevel accuracylevelField;
        
        private PakkeshopData[] parcelshopsField;
        
        /// <remarks/>
        public AccuracyLevel accuracylevel {
            get {
                return this.accuracylevelField;
            }
            set {
                this.accuracylevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PakkeshopData[] parcelshops {
            get {
                return this.parcelshopsField;
            }
            set {
                this.parcelshopsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public enum AccuracyLevel {
        
        /// <remarks/>
        EXACT,
        
        /// <remarks/>
        STREET,
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gls.dk/webservices/")]
    public partial class Break {
        
        private string startField;
        
        private string endField;
        
        /// <remarks/>
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetOneParcelShopCompletedEventHandler(object sender, GetOneParcelShopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOneParcelShopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOneParcelShopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PakkeshopData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PakkeshopData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllParcelShopsCompletedEventHandler(object sender, GetAllParcelShopsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllParcelShopsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllParcelShopsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PakkeshopData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PakkeshopData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetParcelShopsInZipcodeCompletedEventHandler(object sender, GetParcelShopsInZipcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetParcelShopsInZipcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetParcelShopsInZipcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PakkeshopData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PakkeshopData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SearchNearestParcelShopsCompletedEventHandler(object sender, SearchNearestParcelShopsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchNearestParcelShopsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchNearestParcelShopsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ParcelShopSearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ParcelShopSearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetParcelShopDropPointCompletedEventHandler(object sender, GetParcelShopDropPointCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetParcelShopDropPointCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetParcelShopDropPointCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ParcelShopSearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ParcelShopSearchResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591